export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const LOGOUT = 'LOGOUT';
export const TEACHER_REGISTER_SUCCESS = 'TEACHER_REGISTER_SUCCESS';
export const TEACHER_REGISTER_FAIL = 'TEACHER_REGISTER_FAIL';
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS';
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL';
export const STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS';
export const STUDENT_REGISTER_FAIL = 'STUDENT_REGISTER_FAIL';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';

export const EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS';
export const EXAM_CREATE_FAIL = 'EXAM_CREATE_FAIL';
export const EXAM_SHOW_ALL = 'EXAM_SHOW_ALL';
export const EXAM_GET_EDIT = 'EXAM_GET_EDIT';
export const EXAM_UPDATE = 'EXAM_UPDATE';
export const EXAM_PUBLISH = 'EXAM_PUBLISH';

export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS';
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL';

export const STUDENT_GET = 'STUDENT_GET';
export const STUDENT_EXAM = 'STUDENT_EXAM';

export const EXAM_RESULT_CREATE_SUCCESS = 'EXAM_RESULT_CREATE_SUCCESS';
export const EXAM_RESULT_GET_STUDENT_SUCCESS = 'EXAM_RESULT_GET_STUDENT_SUCCESS';
export const EXAM_RESULT_FAIL = 'EXAM_RESULT_FAIL';
