export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const LOGOUT = 'LOGOUT';
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS';
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';

export const EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS';
export const EXAM_CREATE_FAIL = 'EXAM_CREATE_FAIL';
export const EXAM_SHOW_ALL = 'EXAM_SHOW_ALL';
export const EXAM_GET_EDIT = 'EXAM_GET_EDIT';
export const EXAM_UPDATE_SUCCESS = 'EXAM_UPDATE_SUCCESS';
export const EXAM_UPDATE_FAIL = 'EXAM_UPDATE_FAIL';
export const EXAM_PUBLISH = 'EXAM_PUBLISH';
export const EXAM_UNPUBLISH = 'EXAM_UNPUBLISH';
export const EXAM_DELETE = 'EXAM_DELETE';
export const EXAM_TAKE_CODE_SUCCESS = 'EXAM_TAKE_CODE_SUCCESS';
export const EXAM_TAKE_CODE_FAIL = 'EXAM_TAKE_CODE_FAIL';

export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS';
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL';
export const QUESTION_GET_FOR_EDIT = 'QUESTION_GET_FOR_EDIT';
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS';
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL';

export const EXAM_RESULT_CREATE_SUCCESS = 'EXAM_RESULT_CREATE_SUCCESS';
export const EXAM_RESULT_CREATE_FAIL = 'EXAM_RESULT_CREATE_FAIL';
export const EXAM_RESULT_GET_STUDENT_SUCCESS = 'EXAM_RESULT_GET_STUDENT_SUCCESS';
export const EXAM_RESULT_GET_STUDENT_FAIL = 'EXAM_RESULT_GET_STUDENT_FAIL';
export const EXAM_RESULT_FAIL = 'EXAM_RESULT_FAIL';
export const EXAM_RESULT_FINISH = 'EXAM_RESULT_FINISH';
export const EXAM_RESULT_GET_BY_ID = 'EXAM_RESULT_GET_BY_ID';
export const EXAM_RESULT_GET_BY_EXAM_ID = 'EXAM_RESULT_GET_BY_EXAM_ID';

export const ANSWER_CREATE_SUCCESS = 'ANSWER_CREATE_SUCCESS';
export const ANSWER_CREATE_FAIL = 'ANSWER_CREATE_FAIL';
export const ANSWER_UPDATE_SCORE_SUCCESS = 'ANSWER_UPDATE_SCORE_SUCCESS';
export const ANSWER_UPDATE_SCORE_FAIL = 'ANSWER_UPDATE_SCORE_FAIL';

export const TEACHER_GET = 'TEACHER_GET';
export const TEACHER_GET_ALL = 'TEACHER_GET_ALL';
export const TEACHER_CREATE_SUCCESS = 'TEACHER_CREATE_SUCCESS';
export const TEACHER_CREATE_FAIL = 'TEACHER_CREATE_FAIL';
export const TEACHER_UPDATE_SUCCESS = 'TEACHER_UPDATE_SUCCESS';
export const TEACHER_UPDATE_FAIL = 'TEACHER_UPDATE_FAIL';
export const TEACHER_DELETE_SUCCESS = 'TEACHER_DELETE_SUCCESS';
export const TEACHER_DELETE_FAIL = 'TEACHER_DELETE_FAIL';
export const TEACHER_REQUEST_CHANGE_PASSWORD = 'TEACHER_REQUEST_CHANGE_PASSWORD';
export const TEACHER_CHANGE_PASSWORD_SUCCESS = 'TEACHER_CHANGE_PASSWORD_SUCCESS';
export const TEACHER_CHANGE_PASSWORD_FAIL = 'TEACHER_CHANGE_PASSWORD_FAIL';

export const STUDENT_GET = 'STUDENT_GET';
export const STUDENT_GET_ALL = 'STUDENT_GET_ALL';
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS';
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL';
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS';
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL';
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS';
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL';
export const STUDENT_REQUEST_CHANGE_PASSWORD = 'STUDENT_REQUEST_CHANGE_PASSWORD';
export const STUDENT_CHANGE_PASSWORD_SUCCESS = 'STUDENT_CHANGE_PASSWORD_SUCCESS';
export const STUDENT_CHANGE_PASSWORD_FAIL = 'STUDENT_CHANGE_PASSWORD_FAIL';

export const ADMIN_GET = 'ADMIN_GET';

export const MAJOR_GET = 'MAJOR_GET';
export const MAJOR_GET_ALL = 'MAJOR_GET_ALL';
export const MAJOR_CREATE_SUCCESS = 'MAJOR_CREATE_SUCCESS';
export const MAJOR_CREATE_FAIL = 'MAJOR_CREATE_FAIL';
export const MAJOR_UPDATE_SUCCESS = 'MAJOR_UPDATE_SUCCESS';
export const MAJOR_UPDATE_FAIL = 'MAJOR_UPDATE_FAIL';
export const MAJOR_DELETE_SUCCESS = 'MAJOR_DELETE_SUCCESS';
export const MAJOR_DELETE_FAIL = 'MAJOR_DELETE_FAIL';
