export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const LOGOUT = 'LOGOUT';
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS';
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';

export const EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS';
export const EXAM_CREATE_FAIL = 'EXAM_CREATE_FAIL';
export const EXAM_SHOW_ALL = 'EXAM_SHOW_ALL';
export const EXAM_GET_EDIT = 'EXAM_GET_EDIT';
export const EXAM_UPDATE_SUCCESS = 'EXAM_UPDATE_SUCCESS';
export const EXAM_UPDATE_FAIL = 'EXAM_UPDATE_FAIL';
export const EXAM_PUBLISH = 'EXAM_PUBLISH';
export const EXAM_UNPUBLISH = 'EXAM_UNPUBLISH';
export const EXAM_DELETE = 'EXAM_DELETE';
export const EXAM_TAKE_CODE_SUCCESS = 'EXAM_TAKE_CODE_SUCCESS';
export const EXAM_TAKE_CODE_FAIL = 'EXAM_TAKE_CODE_FAIL';

export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS';
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL';
export const QUESTION_GET_FOR_EDIT = 'QUESTION_GET_FOR_EDIT';
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS';
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL';

export const STUDENT_GET = 'STUDENT_GET';

export const EXAM_RESULT_CREATE_SUCCESS = 'EXAM_RESULT_CREATE_SUCCESS';
export const EXAM_RESULT_CREATE_FAIL = 'EXAM_RESULT_CREATE_FAIL';
export const EXAM_RESULT_GET_STUDENT_SUCCESS = 'EXAM_RESULT_GET_STUDENT_SUCCESS';
export const EXAM_RESULT_GET_STUDENT_FAIL = 'EXAM_RESULT_GET_STUDENT_FAIL';
export const EXAM_RESULT_FAIL = 'EXAM_RESULT_FAIL';
export const EXAM_RESULT_FINISH = 'EXAM_RESULT_FINISH';
export const EXAM_RESULT_GET_BY_ID = 'EXAM_RESULT_GET_BY_ID';
export const EXAM_RESULT_GET_BY_EXAM_ID = 'EXAM_RESULT_GET_BY_EXAM_ID';

export const ANSWER_CREATE_SUCCESS = 'ANSWER_CREATE_SUCCESS';
export const ANSWER_CREATE_FAIL = 'ANSWER_CREATE_FAIL';
